### ISSUE TITLE
Unable to read history

### ISSUE THREAD

**Issue by Akegata** [guysoft/OctoPi#144]
My History tab is empty, and I get this in my log:
```
2015-09-06 15:42:38,084 - octoprint - ERROR - Exception on /plugin/printhistory/history [GET]
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_printhistory/__init__.py", line 64, in getHistoryData
    raise IOError("Couldn't read history data from {path}".format(path=self._history_file_path))
IOError: Couldn't read history data from /home/pi/.octoprint/data/printhistory/history.yaml
```

The history.yaml file is accessible to the pi user (and cat'ing it works fine):
```
pi@octopi ~/.octoprint/logs $ ls -lh /home/pi/.octoprint/data/printhistory/history.yaml
-rw-r--r-- 1 pi pi 21K Sep  6 15:42 /home/pi/.octoprint/data/printhistory/history.yaml
```

octoprint is run by the pi user:
```
pi@octopi ~/.octoprint/logs $ ps auxwwf | grep octoprint
pi        2304 18.0  7.6 170728 29236 ?        Sl   10:35  59:12 /home/pi/oprint/bin/python /home/pi/oprint/bin/octoprint --host=127.0.0.1 --port=5000
```

It seems like this would be a permissions issue, but I can't figure out what exactly is causing this.

**Comment by foosel** [comment]
This is a problem with the print history plugin, not with OctoPi or OctoPrint. Please report it in the bug tracker if that plugin.
