### ISSUE TITLE
OctoPiPanel failing to start

### ISSUE THREAD

**Issue by mikestreety** [guysoft/OctoPi#148]
I'm not 100% sure if this is OctoPi relevant or not - but thought I would raise an issue to see if someone could help!

I downloaded `2015-05-05-octopi-wheezy-0.12.0` img of OctoPi and have it currently running on my Raspberry Pi B+.

Once up and running a ran a full `apt-get upgrade` and `apt-get update` whcih spent about 20 minutes updating packages.

I have an Adafruit 2.8" touchscreen connected and wanted to use that as a basic interface.

I ran `scripts/enable-adafruit-display` which worked correctly (terminal is now showing on the screen). However, when I run `scripts/OctoPiPanel` I get the following error:

```
Traceback (most recent call last):
  File "/home/pi/OctoPiPanel/OctoPiPanel.py", line 48, in <module>
    import pygame
  File "/usr/lib/python2.7/dist-packages/pygame/__init__.py", line 99, in <module>
    from pygame.base import *
ImportError: /usr/lib/arm-linux-gnueabihf/libSDL-1.2.so.0: undefined symbol: vc_dispmanx_resource_set_palette
```

Any ideas?

Thanks!

**Comment by mikestreety** [comment]
This was resolved by following these instructions:

https://github.com/jonaslorander/OctoPiPanel#getting-and-installing-octopipanel
