### ISSUE TITLE
Cannot update from 1.2.7

### ISSUE THREAD

**Issue by myoung34** [guysoft/OctoPi#181]
Unmodified version of 1.2.7
Version upgrades via web UI have been successful, this is how my current version has been achieved.

I currently get the new version available prompt, but the version never completes. It immediately returns successful via web ui but version never changes.

octoprint log shows:

```
2015-12-19 02:29:07,390 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

2015-12-19 02:29:08,095 - octoprint.plugins.softwareupdate - ERROR - Could not check octoprint for updates
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.7-py2.7.egg/octoprint/plugins/softwareupdate/__init__.py", line 471, in _get_current_version
    information, is_current = version_checker.get_latest(target, check)
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.7-py2.7.egg/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 140, in get_latest
    force_base=force_base)
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.7-py2.7.egg/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 93, in _is_current
    sanitized_local = _get_sanitized_version(release_information["local"]["value"])
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.7-py2.7.egg/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 48, in _get_sanitized_version
    if "-" in version_string:
TypeError: argument of type 'NoneType' is not iterable
2015-12-19 02:29:08,150 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk

```

**Comment by myoung34** [comment]
Closing. No clue why I put this here. It should (and is) be on the octoprint page.
Even has an issue for it already: https://github.com/foosel/OctoPrint/issues/1135

Keep up the good work!
