### ISSUE TITLE
Plugin Manager error on latest version

### ISSUE THREAD

**Issue by cbrherms** [guysoft/OctoPi#293]
Downloaded and set up OctoPi image last night, once done i noticed that the plugin manager wouldn't connect to the plugin repository, saying that the repository is not available.

Upon looking at the start up logs i've seen the following:

`2017-01-17 10:09:21,314 - octoprint.plugin - ERROR - Error while calling plugin pluginmanager
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugin/__init__.py", line 229, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugins/pluginmanager/__init__.py", line 82, in on_startup
    self._repository_available = self._fetch_repository_from_disk()
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugins/pluginmanager/__init__.py", line 568, in _fetch_repository_from_disk
    return self._refresh_repository(repo_data=repo_data)
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugins/pluginmanager/__init__.py", line 620, in _refresh_repository
    self._repository_plugins = map(map_repository_entry, repo_data)
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugins/pluginmanager/__init__.py", line 613, in map_repository_entry
    result["is_compatible"]["octoprint"] = self._is_octoprint_compatible(octoprint_version, entry["compatibility"]["octoprint"])
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.0.post1_g1014712-py2.7.egg/octoprint/plugins/pluginmanager/__init__.py", line 632, in _is_octoprint_compatible
    s = next(pkg_resources.parse_requirements("OctoPrint" + octo_compat))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pkg_resources.py", line 2697, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ("Expected ',' or end-of-list in", 'OctoPrint>=1.2.6+', 'at', '+')`

**Comment by guillaumemolter** [comment]
+1

**Comment by Cyberman-tM** [comment]
Same here I think. I tried updating to 1.3.0 with out success.
Which Raspi do you have? I've a Raspi 3.

**Comment by cbrherms** [comment]
RasPi 3 also

**Comment by guysoft** [comment]
This is an OctoPrint issue, not an OctoPi, issue, please post it to https://github.com/foosel/OctoPrint/issues/

**Comment by guysoft** [comment]
cc @foosel  people here, didnt redirect them in time

**Comment by foosel** [comment]
Already solved, was an issue with the version string in an updated plugin entry.
