### ISSUE TITLE
Update attempt on version 1.6.1 fails 

### ISSUE THREAD

**Issue by PatrickMans** [guysoft/OctoPi#836]
I have installed octoprint on a raspberry pi 4B (2GB) and used that for quite some time a few years back. For over a year, I have not used my 3D printer so octoprint has unused since then. I am currently still running version 1.6.1. 
I have been trying to upgrade the software to the newest version, without any luck. 

The logging shows: 
`2024-09-04 14:43:43,822 ! ERROR: Command errored out with exit status 1:
2024-09-04 14:43:43,823 ! command: /home/pi/oprint/bin/python2 /home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpxNdofn
2024-09-04 14:43:43,826 ! cwd: /tmp/pip-req-build-4mfrOS
2024-09-04 14:43:43,827 ! Complete output (19 lines):
2024-09-04 14:43:43,829 ! Traceback (most recent call last):
2024-09-04 14:43:43,829 ! File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
2024-09-04 14:43:43,831 ! main()
2024-09-04 14:43:43,832 ! File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
2024-09-04 14:43:43,832 ! json_out['return_val'] = hook(**hook_input['kwargs'])
2024-09-04 14:43:43,833 ! File "/home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
2024-09-04 14:43:43,833 ! return hook(config_settings)
2024-09-04 14:43:43,833 ! File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
2024-09-04 14:43:43,834 ! return self._get_build_requires(config_settings, requirements=['wheel'])
2024-09-04 14:43:43,834 ! File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
2024-09-04 14:43:43,835 ! self.run_setup()
2024-09-04 14:43:43,835 ! File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
2024-09-04 14:43:43,835 ! self).run_setup(setup_script=setup_script)
2024-09-04 14:43:43,835 ! File "/home/pi/oprint/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
2024-09-04 14:43:43,836 ! exec(compile(code, __file__, 'exec'), locals())
2024-09-04 14:43:43,836 ! File "setup.py", line 464
2024-09-04 14:43:43,837 ! f"Copying translations for locale {locale} from {source_path} to {target_path}..."
2024-09-04 14:43:43,837 ! ^
2024-09-04 14:43:43,837 ! SyntaxError: invalid syntax
2024-09-04 14:43:43,838 ! ----------------------------------------
2024-09-04 14:43:43,838 ! ERROR: Command errored out with exit status 1: /home/pi/oprint/bin/python2 /home/pi/oprint/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpxNdofn Check the logs for full command output.
2024-09-04 14:43:43,857   /home/pi/oprint/bin/python2 -m pip --disable-pip-version-check install https://github.com/OctoPrint/OctoPrint-PiSupport/archive/2023.10.10.zip --no-cache-dir
2024-09-04 14:43:46,107 > Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2024-09-04 14:43:46,108 > Collecting https://github.com/OctoPrint/OctoPrint-PiSupport/archive/2023.10.10.zip
2024-09-04 14:43:46,124 > Downloading https://github.com/OctoPrint/OctoPrint-PiSupport/archive/2023.10.10.zip
2024-09-04 14:43:46,791 ! ERROR: Command errored out with exit status 1:
2024-09-04 14:43:46,792 ! command: /home/pi/oprint/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-JXL8Za/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-JXL8Za/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-JXL8Za/pip-egg-info
2024-09-04 14:43:46,793 ! cwd: /tmp/pip-req-build-JXL8Za/
2024-09-04 14:43:46,794 ! Complete output (6 lines):
2024-09-04 14:43:46,794 ! Traceback (most recent call last):
2024-09-04 14:43:46,795 ! File "<string>", line 1, in <module>
2024-09-04 14:43:46,795 ! File "/tmp/pip-req-build-JXL8Za/setup.py", line 454
2024-09-04 14:43:46,795 ! f"Copying translations for locale {locale} from {source_path} to {target_path}..."
2024-09-04 14:43:46,795 ! ^
2024-09-04 14:43:46,796 ! SyntaxError: invalid syntax
2024-09-04 14:43:46,796 ! ----------------------------------------
2024-09-04 14:43:46,796 ! ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.` 

How can I overcome this? Do i need to update to intermediate versions,  or do a fresh install of the software on the pi?

Thanks,
Patrick.

**Comment by guysoft** [comment]
This is an OctoPi issue tracker, for the OctoPrint issue tracker take a look at:
https://github.com/OctoPrint/OctoPrint/issues

A syntax error might suggest you are using an deprecated version of python, what version of OctoPi are you using?

**Comment by PatrickMans** [comment]
On the octoprint github repo it clearly states:
"If you want to run OctoPrint on a Raspberry Pi, you really should take a look at [OctoPi](https://github.com/guysoft/OctoPi) which is a custom SD card image that includes OctoPrint plus dependencies."

I rebuild a new sdcard with the latest version and even there I have not succeeded in getting it to work.

**Comment by guysoft** [comment]
@PatrickMans I don't understand what you mean by "rebuilding" - did you flash the latest rpi image on an sd card? 
Also you did not provide the version of OctoPi, so I am not sure what you are using and how new or old it is.

**Comment by PatrickMans** [comment]
Indeed, i flashed the latest image on a new clean sd card.

**Comment by guysoft** [comment]
@PatrickMans What is the latest image you are using? There is a stable version and a nightly.
